#!/usr/bin/env python3
"""The agents Revenant knows how to find, read and resume.

Each agent keeps one transcript file per conversation somewhere under a config
directory. An `Agent` describes where that is, how to pull the working directory
and prompts out of a transcript, how to tell which conversations are still
running, and what command brings one back.

Adding an agent means one subclass and one line in `AGENTS`.
"""

from __future__ import annotations

import json
import os
import re
import sqlite3
from collections import defaultdict
from dataclasses import dataclass, field as dataclass_field
from datetime import datetime, timezone
from pathlib import Path
from typing import Iterable, Iterator

# Records at the head of a transcript that carry cwd, version and branch.
HEAD_LINES = 80
# Bytes read from the end of a transcript when the prompt index has no entry for it.
TAIL_BYTES = 256 * 1024

#: How far back to keep widening the search for something the user typed before
#: giving up on a transcript. Past this the file is pathological and finishing the
#: scan matters more than the one row.
SEARCH_CAP = 32 * 1024 * 1024

#: Lines that could carry a Codex prompt, tested as bytes so that widening the
#: window costs a substring scan rather than a JSON decode per record.
_CODEX_PROMPT_HINTS = (b"user_message", b'"user"')

#: Claude Code appends the session's name to the transcript whenever it changes,
#: as one record per kind. Highest priority first: a name the user set with
#: `/rename` beats a title the model generated, which beats the agent's own name.
TITLE_RECORDS = (("custom-title", "customTitle"), ("ai-title", "aiTitle"), ("agent-name", "agentName"))

_TITLE_TYPES = frozenset(kind for kind, _ in TITLE_RECORDS)
# Where a session's name is looked for first. Every named transcript on a real
# machine kept its name within the last few pages; the full tail is the fallback.
TITLE_BYTES = 64 * 1024

#: Session name by (path, mtime, size), so a rescan of an unchanged transcript
#: costs nothing. Cleared wholesale rather than evicted one by one: it is a cache
#: for one listing, not a store.
_TITLE_CACHE: dict[tuple[str, int, int], str] = {}
_TITLE_CACHE_MAX = 4096


def _stamp(path: Path) -> tuple[str, int, int] | None:
    """A key that changes whenever the file does."""
    try:
        info = path.stat()
    except OSError:
        return None
    return (str(path), info.st_mtime_ns, info.st_size)


def _remember_title(key: tuple[str, int, int] | None, title: str) -> str:
    if key is not None:
        if len(_TITLE_CACHE) >= _TITLE_CACHE_MAX:
            _TITLE_CACHE.clear()
        _TITLE_CACHE[key] = title
    return title


def _collect_title(record: dict, into: dict[str, str]) -> None:
    for _, field in TITLE_RECORDS:
        value = record.get(field)
        if isinstance(value, str) and value.strip():
            into[field] = value.strip()


def _best_title(names: dict[str, str]) -> str:
    for _, field in TITLE_RECORDS:
        if field in names:
            return clean_prompt(names[field], limit=80)
    return ""


# Harness plumbing that lands in the transcript looking like something the user
# typed. Both agents inject plenty, in two shapes.
#
# A tag whose name carries a hyphen or an underscore: every one of these is
# machinery (<task-notification>, <environment_context>, <bash-input>), while the
# tags a person might actually open a message with are bare words (<div>, <html>).
# `skill` and `image` are the two bare ones worth naming.
_META_PROMPT = re.compile(
    r"^\s*<([a-z][a-z0-9]*[-_][a-z0-9_-]*|skill|image)[>\s]", re.I
)

#: And plain prose an agent writes into the user's side of the conversation.
_INJECTED_PROMPT = (
    "the following is the codex agent history",
    "this session is being continued from a previous conversation",
    "stop hook feedback:",
    "a session-scoped stop hook is now active",
    "base directory for this skill:",
    "another claude session sent a message:",
    "caveat: the messages below were generated by the user",
    "[request interrupted by user]",
    "[image: original",
)
_UUID = re.compile(r"[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}", re.I)


def clean_prompt(text: object, *, limit: int = 160) -> str:
    """Flatten a prompt to one printable line."""
    if not isinstance(text, str):
        return ""
    flat = " ".join(text.split())
    return flat[: limit - 1] + "…" if len(flat) > limit else flat


def is_meaningful(prompt: str) -> bool:
    """True for prompts a person actually typed, not slash commands or harness noise."""
    if not prompt or _META_PROMPT.match(prompt):
        return False
    if prompt.lstrip()[:64].lower().startswith(_INJECTED_PROMPT):
        return False
    return not prompt.startswith("/")


def from_iso(value: object) -> datetime | None:
    if not isinstance(value, str):
        return None
    try:
        parsed = datetime.fromisoformat(value.replace("Z", "+00:00"))
    except ValueError:
        return None
    return parsed if parsed.tzinfo else parsed.replace(tzinfo=timezone.utc)


def from_epoch(value: object) -> datetime | None:
    """Read a timestamp that may be in seconds or milliseconds."""
    try:
        number = float(value)  # type: ignore[arg-type]
    except (TypeError, ValueError):
        return None
    if number > 1e11:  # milliseconds
        number /= 1000
    try:
        return datetime.fromtimestamp(number, tz=timezone.utc)
    except (OSError, OverflowError, ValueError):
        return None


def _records(path: Path, *, limit: int | None = None) -> Iterator[dict]:
    """Yield JSON objects from a JSONL file, skipping anything unreadable."""
    try:
        handle = path.open(encoding="utf-8", errors="replace")
    except OSError:
        return
    with handle:
        for index, line in enumerate(handle):
            if limit is not None and index >= limit:
                return
            try:
                record = json.loads(line)
            except json.JSONDecodeError:
                continue
            if isinstance(record, dict):
                yield record


def _lines_with(blob: bytes, needles: Iterable[bytes]) -> list[bytes]:
    """The whole lines of `blob` holding any of `needles`, in file order.

    Found with `bytes.find`, so the lines without one are never cut out at all.
    A rollout's tail is hundreds of thousands of lines of tool traffic around a
    handful of prompts, and splitting all of it to test each line was most of
    the cost of a scan.
    """
    starts: set[int] = set()
    for needle in needles:
        at = blob.find(needle)
        while at >= 0:
            starts.add(blob.rfind(b"\n", 0, at) + 1)
            end = blob.find(b"\n", at)
            if end < 0:
                break
            at = blob.find(needle, end)
    lines = []
    for start in sorted(starts):
        end = blob.find(b"\n", start)
        lines.append(blob[start:end if end >= 0 else len(blob)].rstrip(b"\r"))
    return lines


def _tail_lines(path: Path, *, window: int, containing: Iterable[bytes] = ()) -> Iterator[bytes]:
    """Yield whole lines from the last `window` bytes of a file, as raw bytes.

    With `containing`, only the lines that hold one of those byte strings, which
    is how a caller after a few kinds of record skips both the parsing and the
    splitting of the rest.
    """
    try:
        size = path.stat().st_size
        with path.open("rb") as handle:
            if size > window:
                handle.seek(size - window)
                handle.readline()  # drop the partial line
            blob = handle.read()
    except OSError:
        return
    needles = tuple(containing)
    yield from (_lines_with(blob, needles) if needles else blob.splitlines())


def _tail_records(path: Path, *, window: int) -> Iterator[dict]:
    """Yield JSON objects from the last `window` bytes of a JSONL file."""
    for line in _tail_lines(path, window=window):
        try:
            record = json.loads(line.decode("utf-8", errors="replace"))
        except json.JSONDecodeError:
            continue
        if isinstance(record, dict):
            yield record


def _query(path: Path, sql: str, parameters: tuple = ()) -> list[dict]:
    """Read a database, including its WAL, without creating or migrating it."""
    try:
        if not path.is_file():
            return []
        connection = sqlite3.connect(path.resolve().as_uri() + "?mode=ro", uri=True, timeout=0.2)
        try:
            connection.row_factory = sqlite3.Row
            connection.execute("PRAGMA query_only = ON")
            return [dict(row) for row in connection.execute(sql, parameters)]
        finally:
            connection.close()
    except (OSError, sqlite3.Error):
        # Old schemas, interrupted migrations and locked databases must not hide
        # the transcripts that can still be read independently.
        return []


def _object(value: object) -> dict:
    """Decode an optional JSON object from disk; damaged records are empty."""
    if isinstance(value, dict):
        return value
    if isinstance(value, str):
        try:
            parsed = json.loads(value)
        except (ValueError, TypeError):
            return {}
        return parsed if isinstance(parsed, dict) else {}
    return {}


def _read_object(path: Path) -> dict:
    try:
        return _object(path.read_text(encoding="utf-8"))
    except (OSError, UnicodeError):
        return {}


def _user_text(content: object) -> str:
    """Discard harness blocks before flattening a multipart user message."""
    if isinstance(content, list):
        texts = []
        for part in content:
            if not isinstance(part, dict):
                continue
            text = clean_prompt(part.get("text"))
            if is_meaningful(text) and not text.startswith("# AGENTS.md instructions"):
                texts.append(text)
        content = " ".join(texts)
    text = clean_prompt(content)
    return text if is_meaningful(text) and not text.startswith("# AGENTS.md instructions") else ""


@dataclass
class SessionSource:
    """One conversation backed by a transcript or a row in a shared database."""

    session_id: str
    transcript: Path
    group: str
    modified: datetime
    size: int = 0
    metadata: dict = dataclass_field(default_factory=dict)
    prompts: tuple[str, str, int, bool] | None = None
    title: str = ""
    fallback_prompt: str = ""


class Agent:
    """One coding agent. Subclasses fill in the file formats."""

    key = "agent"
    label = "Agent"
    env_var = ""
    resume_template = "{id}"
    #: Where a config directory lives when the environment variable is unset.
    home_relative = ".agent"
    #: Glob for transcripts, relative to the config directory.
    transcript_glob = "*.jsonl"
    #: Seconds of recent activity that count as "may still be running" for agents
    #: that keep no registry of live sessions. Zero means the registry is the only
    #: signal.
    live_window = 0.0
    #: Process images a live session can run under, guarding against PID reuse.
    process_images = frozenset({"node", "node.exe"})
    #: One line explaining how liveness is decided, shown in the UI.
    liveness_note = ""
    #: Some agents index only CLI input while also accepting desktop/editor turns.
    history_is_partial = False

    def __init__(self, *, process_images: Iterable[str] | None = None) -> None:
        if process_images is not None:
            self.process_images = frozenset(process_images)

    # -- identity --------------------------------------------------------- #

    def __repr__(self) -> str:  # pragma: no cover - debugging aid
        return f"<{type(self).__name__} {self.key}>"

    def variant(self, **overrides) -> Agent:
        """A copy with attributes replaced. Used by tests and the demo recorder."""
        clone = type(self)()
        for name, value in overrides.items():
            if name == "process_images":
                value = frozenset(value)
            setattr(clone, name, value)
        return clone

    def config_dir(self, explicit: str | os.PathLike[str] | None = None) -> Path:
        if explicit:
            return Path(explicit).expanduser()
        env = os.environ.get(self.env_var) if self.env_var else None
        return Path(env).expanduser() if env else Path.home() / self.home_relative

    def resume_command(self, session_id: str) -> str:
        return self.resume_template.format(id=session_id)

    def installed(self) -> bool:
        return self.config_dir().is_dir()

    # -- discovery -------------------------------------------------------- #

    def transcripts(self, root: Path) -> Iterator[Path]:
        yield from root.glob(self.transcript_glob)

    def sources(self, root: Path, *, since: datetime, until: datetime | None = None) -> Iterator[SessionSource]:
        """File-backed sessions; database agents override this adapter."""
        for path in self.transcripts(root):
            try:
                info = path.stat()
                modified = datetime.fromtimestamp(info.st_mtime, tz=timezone.utc)
            except (OSError, ValueError, OverflowError):
                continue
            yield SessionSource(self.session_id(path), path, self.group(path), modified, info.st_size)

    def activity(self, root: Path, session_id: str, transcript: Path) -> datetime | None:
        """Per-session activity for the final liveness check, never a shared DB mtime."""
        try:
            return datetime.fromtimestamp(transcript.stat().st_mtime, tz=timezone.utc)
        except (OSError, ValueError, OverflowError):
            return None

    def session_id(self, transcript: Path) -> str:
        return transcript.stem

    def root_of(self, transcript: Path) -> Path:
        """The config directory this transcript was found under.

        Derived from the glob's depth so that it stays right for `--root` and for
        any agent added later. A path too short to hold that depth is not one of
        ours, so the best answer available is where it sits.
        """
        parents = transcript.parents
        depth = self.transcript_glob.count("/")
        return parents[depth] if depth < len(parents) else transcript.parent

    def group(self, transcript: Path) -> str:
        """A short label for where the transcript is filed, used as a fallback name."""
        return transcript.parent.name

    def head(self, transcript: Path) -> dict:
        """Working directory, version, branch and start time from the first records."""
        raise NotImplementedError

    def tail(self, transcript: Path) -> tuple[str, str, int, bool]:
        """(first, last, count, complete) prompts, read from the end of the file."""
        raise NotImplementedError

    def history(self, root: Path) -> dict[str, list[tuple[datetime, str, str]]]:
        """sessionId -> [(when, prompt, project)] from the agent's prompt index."""
        return {}

    def title(self, transcript: Path) -> str:
        """The session's own name, read from its transcript. Empty when it has none."""
        return ""

    def titles(self, root: Path) -> dict[str, str]:
        """sessionId -> name, for agents that keep names in one index file."""
        return {}

    def live_registry(self, root: Path) -> dict[str, dict]:
        """sessionId -> {pid, cwd, name, status} for sessions the agent says are running."""
        return {}


class ClaudeCode(Agent):
    """Anthropic's Claude Code CLI.

    Transcripts live at `projects/<slug>/<uuid>.jsonl`; running sessions are
    registered in `sessions/<pid>.json` and that registry is pruned on startup, so
    after a crash it is empty and the transcripts are all that is left.
    """

    key = "claude-code"
    label = "Claude Code"
    env_var = "CLAUDE_CONFIG_DIR"
    home_relative = ".claude"
    transcript_glob = "projects/*/*.jsonl"
    resume_template = "claude --resume {id}"
    process_images = frozenset({"claude.exe", "claude", "node.exe", "node", "bun.exe", "bun"})
    liveness_note = "running sessions register themselves, so this is exact"

    def head(self, transcript: Path) -> dict:
        """Working directory, version, branch and start time from the first records.

        Claude Code writes all four onto its first real record, so this normally
        stops after two or three. The wider budget is only for a transcript that
        opens with a run of harness records, and outside a repository there is no
        branch to find, so that case reads to the limit as it always did.
        """
        meta: dict = {}
        for index, record in enumerate(_records(transcript, limit=HEAD_LINES * 8)):
            for key in ("cwd", "version", "gitBranch"):
                if key not in meta and record.get(key):
                    meta[key] = record[key]
            if "started" not in meta:
                started = from_iso(record.get("timestamp"))
                if started:
                    meta["started"] = started
            if "cwd" in meta and "started" in meta and (len(meta) == 4 or index >= HEAD_LINES):
                break
        return meta

    def _read_tail(self, transcript: Path, window: int) -> tuple[list[str], dict[str, str]]:
        """What the user typed within the last `window` bytes, and any names seen."""
        prompts: list[str] = []
        names: dict[str, str] = {}
        # Parsing every tool result to find the odd prompt costs more than the rest
        # of the scan; a user record always says "user".
        wanted = (b'"user"', *(kind.encode() for kind in _TITLE_TYPES))
        for line in _tail_lines(transcript, window=window, containing=wanted):
            try:
                record = json.loads(line.decode("utf-8", errors="replace"))
            except json.JSONDecodeError:
                continue
            if not isinstance(record, dict):
                continue
            kind = record.get("type")
            if kind in _TITLE_TYPES:
                _collect_title(record, names)
                continue
            if kind != "user" or record.get("isMeta") or record.get("isSidechain"):
                continue
            content = (record.get("message") or {}).get("content")
            if isinstance(content, list):
                # Tool results come back as user-role messages too, and carry no
                # text part, so they flatten to nothing and fall away below.
                content = " ".join(p.get("text", "") for p in content if isinstance(p, dict))
            text = clean_prompt(content)
            if is_meaningful(text):
                prompts.append(text)
        return prompts, names

    def tail(self, transcript: Path) -> tuple[str, str, int, bool]:
        """The prompts, and the session's name as a side effect.

        One pass over one window answers both questions, so `title()` below finds
        the answer waiting for it instead of reading the same bytes again.

        A long agentic run puts thousands of tool results between two things the
        user typed, and the end of such a file holds none of the latter. The
        window widens until it finds one rather than reporting an empty session.
        """
        try:
            size = transcript.stat().st_size
        except OSError:
            return "", "", 0, False

        window = TAIL_BYTES
        names: dict[str, str] = {}
        while True:
            whole = window >= size
            prompts, seen = self._read_tail(transcript, window)
            names = seen or names
            if prompts or whole or window >= SEARCH_CAP:
                break
            window = min(window * 8, SEARCH_CAP)

        _remember_title(_stamp(transcript), _best_title(names))
        if not prompts:
            return "", "", 0, whole
        return (prompts[0] if whole else ""), prompts[-1], len(prompts), whole

    def title(self, transcript: Path) -> str:
        """The name shown in Claude Code's own session picker.

        Naming records are rewritten on almost every turn, so the last one in the
        file is current and the end of the file is the cheap place to look. The
        first pass reads a few pages, which is where every named session on a real
        machine turned out to keep its name; the full window is the fallback.
        """
        key = _stamp(transcript)
        if key is not None and key in _TITLE_CACHE:
            return _TITLE_CACHE[key]

        found = self._scan_title(transcript, TITLE_BYTES)
        if not found and key is not None and key[2] > TITLE_BYTES:
            found = self._scan_title(transcript, TAIL_BYTES)
        return _remember_title(key, found)

    def _scan_title(self, transcript: Path, window: int) -> str:
        kinds = [kind.encode() for kind, _ in TITLE_RECORDS]
        names: dict[str, str] = {}
        # Parsing every record here would cost more than the whole scan does.
        for raw in _tail_lines(transcript, window=window, containing=kinds):
            try:
                record = json.loads(raw)
            except (json.JSONDecodeError, UnicodeDecodeError):
                continue
            # A damaged file can leave a bare string or list on a line of its own.
            if isinstance(record, dict):
                _collect_title(record, names)
        return _best_title(names)

    def history(self, root: Path) -> dict[str, list[tuple[datetime, str, str]]]:
        index: dict[str, list[tuple[datetime, str, str]]] = defaultdict(list)
        for record in _records(root / "history.jsonl"):
            session_id = record.get("sessionId")
            when = from_epoch(record.get("timestamp"))
            if session_id and when:
                index[session_id].append(
                    (when, clean_prompt(record.get("display")), record.get("project") or "")
                )
        for entries in index.values():
            entries.sort(key=lambda item: item[0])
        return index

    def live_registry(self, root: Path) -> dict[str, dict]:
        directory = root / "sessions"
        if not directory.is_dir():
            return {}
        found: dict[str, dict] = {}
        for path in directory.glob("*.json"):
            try:
                record = json.loads(path.read_text(encoding="utf-8", errors="replace"))
            except (OSError, json.JSONDecodeError):
                continue
            if isinstance(record, dict) and record.get("sessionId") and record.get("pid"):
                found[record["sessionId"]] = record
        return found


class Codex(Agent):
    """OpenAI's Codex CLI.

    Transcripts live at `sessions/<year>/<month>/<day>/rollout-<stamp>-<uuid>.jsonl`.
    Codex keeps no registry of running sessions, so a conversation that was written
    to moments ago is treated as possibly still open.
    """

    key = "codex"
    label = "Codex"
    env_var = "CODEX_HOME"
    home_relative = ".codex"
    transcript_glob = "sessions/*/*/*/rollout-*.jsonl"
    resume_template = "codex resume {id}"
    live_window = 120.0
    process_images = frozenset({"codex.exe", "codex", "node.exe", "node"})
    liveness_note = "Codex keeps no registry, so anything touched in the last 2 minutes is held back"
    history_is_partial = True

    def transcripts(self, root: Path) -> Iterator[Path]:
        for directory in ("sessions", "archived_sessions"):
            yield from (root / directory).rglob("rollout-*.jsonl")

    def root_of(self, transcript: Path) -> Path:
        for parent in transcript.parents:
            if parent.name in {"sessions", "archived_sessions"}:
                return parent.parent
        return transcript.parent

    def activity(self, root: Path, session_id: str, transcript: Path) -> datetime | None:
        modified = super().activity(root, session_id, transcript)
        row = next((row for row in self._threads(root) if row.get("id") == session_id), {})
        updated = from_epoch(row.get("updated_at_ms")) or from_epoch(row.get("updated_at"))
        return max(modified, updated) if modified and updated else modified or updated

    @staticmethod
    def _threads(root: Path) -> list[dict]:
        databases = sorted(root.glob("state_*.sqlite"), key=lambda p: int(p.stem.split("_")[-1])
                           if p.stem.split("_")[-1].isdigit() else -1, reverse=True)
        for database in databases:
            rows = _query(database, "SELECT * FROM threads")
            if rows:
                return rows
        return []

    def sources(self, root: Path, *, since: datetime, until: datetime | None = None) -> Iterator[SessionSource]:
        threads = {row["id"]: row for row in self._threads(root) if row.get("id")}
        indexed_paths = {Path(row["rollout_path"]) if Path(row["rollout_path"]).is_absolute()
                         else root / row["rollout_path"]: row
                         for row in threads.values() if isinstance(row.get("rollout_path"), str)}
        paths = [*indexed_paths, *self.transcripts(root)]
        seen: set[str] = set()
        for path in dict.fromkeys(paths):
            row = indexed_paths.get(path, threads.get(self.session_id(path), {}))
            session_id = row.get("id") or self.session_id(path)
            if row and (not isinstance(session_id, str) or not _UUID.fullmatch(session_id)):
                continue
            try:
                info = path.stat()
                modified = datetime.fromtimestamp(info.st_mtime, tz=timezone.utc)
            except (OSError, ValueError, OverflowError):
                continue
            if session_id in seen:
                continue
            seen.add(session_id)
            # Desktop metadata can have a newer cwd and activity than the rollout.
            updated = from_epoch(row.get("updated_at_ms")) or from_epoch(row.get("updated_at"))
            modified = max(modified, updated) if updated else modified
            metadata = {"cwd": row.get("cwd"), "version": row.get("cli_version"),
                        "gitBranch": row.get("git_branch"),
                        "started": from_epoch(row.get("created_at_ms")) or from_epoch(row.get("created_at"))}
            fallback = _user_text(row.get("first_user_message"))
            # Preserve evidence of a real conversation even when a long tool run
            # pushes its prompt outside the bounded transcript search.
            yield SessionSource(session_id, path, self.group(path), modified, info.st_size,
                                metadata, title=clean_prompt(row.get("name") or row.get("title"), limit=80),
                                fallback_prompt=fallback)

    def session_id(self, transcript: Path) -> str:
        match = _UUID.search(transcript.stem)
        return match.group(0) if match else transcript.stem

    def group(self, transcript: Path) -> str:
        return "codex"

    def head(self, transcript: Path) -> dict:
        meta: dict = {}
        # session_meta is the first record, and it carries a large instruction blob,
        # so reading further would cost real time for nothing.
        for record in _records(transcript, limit=4):
            if record.get("type") != "session_meta":
                continue
            payload = _object(record.get("payload"))
            if payload.get("cwd"):
                meta["cwd"] = payload["cwd"]
            if payload.get("cli_version"):
                meta["version"] = payload["cli_version"]
            started = from_iso(payload.get("timestamp")) or from_iso(record.get("timestamp"))
            if started:
                meta["started"] = started
            git = _object(payload.get("git"))
            if git.get("branch"):
                meta["gitBranch"] = git["branch"]
            break
        return meta

    @staticmethod
    def _prompt_of(record: dict) -> str:
        """The text a person typed, or "" for anything else in the rollout."""
        payload = _object(record.get("payload"))
        if record.get("type") == "event_msg" and payload.get("type") == "user_message":
            return _user_text(payload.get("message") or payload.get("text"))
        if (
            record.get("type") == "response_item"
            and payload.get("type") == "message"
            and payload.get("role") == "user"
        ):
            return _user_text(payload.get("content"))
        return ""

    def _prompts_near_the_end(self, transcript: Path, window: int) -> list[str]:
        """What the user typed within the last `window` bytes, in order.

        Codex records each prompt twice, as an event and again as a response
        item, and the pair is adjacent, so a repeat of the line before it is the
        same prompt rather than a second one.
        """
        prompts: list[str] = []
        previous_kind: str | None = None
        for line in _tail_lines(transcript, window=window, containing=_CODEX_PROMPT_HINTS):
            try:
                record = json.loads(line.decode("utf-8", errors="replace"))
            except json.JSONDecodeError:
                continue
            if not isinstance(record, dict):
                continue
            text = self._prompt_of(record)
            if is_meaningful(text):
                kind = record.get("type")
                # Only the event/response pair is a duplicate. Typing the same
                # prompt on two separate turns still counts as two turns.
                if prompts and text == prompts[-1] and previous_kind and previous_kind != kind:
                    previous_kind = None
                else:
                    prompts.append(text)
                    previous_kind = kind
        return prompts

    def tail(self, transcript: Path) -> tuple[str, str, int, bool]:
        try:
            size = transcript.stat().st_size
        except OSError:
            return "", "", 0, False

        # A rollout holds thousands of assistant records between two things the
        # user typed, so a window sized for a chat-shaped transcript can land
        # wholly inside one answer and come back with nothing to identify the
        # session by. Widen until something turns up or the file runs out.
        window = TAIL_BYTES
        while True:
            whole = window >= size
            prompts = self._prompts_near_the_end(transcript, window)
            if prompts:
                return (prompts[0] if whole else ""), prompts[-1], len(prompts), whole
            if whole or window >= SEARCH_CAP:
                return "", "", 0, whole
            window = min(window * 8, SEARCH_CAP)

    def history(self, root: Path) -> dict[str, list[tuple[datetime, str, str]]]:
        index: dict[str, list[tuple[datetime, str, str]]] = defaultdict(list)
        for record in _records(root / "history.jsonl"):
            session_id = record.get("session_id")
            when = from_epoch(record.get("ts"))
            if session_id and when:
                index[session_id].append((when, clean_prompt(record.get("text")), ""))
        for entries in index.values():
            entries.sort(key=lambda item: item[0])
        projected: dict[str, list[tuple[datetime, str, str]]] = defaultdict(list)
        for row in _query(root / "thread_history_1.sqlite",
                          "SELECT thread_id, created_at_ms, item_json FROM thread_items "
                          "WHERE item_type = 'userMessage' ORDER BY thread_id, rollout_ordinal"):
            when = from_epoch(row.get("created_at_ms"))
            text = _user_text(_object(row.get("item_json")).get("content"))
            if when and text:
                projected[row["thread_id"]].append((when, text, ""))
        for session_id, entries in projected.items():
            # The CLI history is sparse for desktop sessions. The projected
            # history holds actual turns, without the event/response duplicates.
            newer = [entry for entry in index.get(session_id, []) if entry[0] > entries[-1][0]]
            index[session_id] = entries + newer
        return index


    def titles(self, root: Path) -> dict[str, str]:
        """Codex names threads in one index file rather than in the rollouts."""
        found: dict[str, str] = {}
        for record in _records(root / "session_index.jsonl"):
            name = record.get("thread_name")
            if record.get("id") and isinstance(name, str) and name.strip():
                found[record["id"]] = clean_prompt(name, limit=80)
        return found


class OpenCode(Agent):
    """OpenCode's shared SQLite store and the JSON store used before migration."""

    key = "opencode"
    label = "OpenCode"
    home_relative = ".local/share/opencode"
    transcript_glob = "storage/session/*/*.json"
    resume_template = "opencode --session {id}"
    live_window = 120.0
    process_images = frozenset({"opencode", "opencode.exe", "bun", "bun.exe", "node", "node.exe"})
    liveness_note = "OpenCode keeps no live registry; sessions active in the last 2 minutes are held back"

    def config_dir(self, explicit: str | os.PathLike[str] | None = None) -> Path:
        if explicit:
            return Path(explicit).expanduser()
        data_home = os.environ.get("XDG_DATA_HOME")
        return Path(data_home).expanduser() / "opencode" if data_home else Path.home() / self.home_relative

    def transcripts(self, root: Path) -> Iterator[Path]:
        yield from (root / "storage" / "session").rglob("*.json")

    def root_of(self, transcript: Path) -> Path:
        if transcript.name == "opencode.db":
            return transcript.parent
        for parent in transcript.parents:
            if parent.name == "storage":
                return parent.parent
        return transcript.parent

    def head(self, transcript: Path) -> dict:
        record = _read_object(transcript)
        return {"cwd": record.get("directory"), "version": record.get("version"),
                "started": from_epoch(_object(record.get("time")).get("created"))}

    def title(self, transcript: Path) -> str:
        return clean_prompt(_read_object(transcript).get("title"), limit=80)

    @staticmethod
    def _summary(prompts: list[str]) -> tuple[str, str, int, bool]:
        return (prompts[0], prompts[-1], len(prompts), True) if prompts else ("", "", 0, True)

    @staticmethod
    def _part_text(part: dict) -> str:
        if part.get("type") == "text" and not part.get("synthetic") and not part.get("ignored"):
            return _user_text(part.get("text"))
        return ""

    def tail(self, transcript: Path) -> tuple[str, str, int, bool]:
        storage = self.root_of(transcript) / "storage"
        prompts: list[str] = []
        for message in sorted((storage / "message" / transcript.stem).glob("*.json")):
            record = _read_object(message)
            if record.get("role") != "user":
                continue
            parts = [self._part_text(_read_object(part)) for part in
                     sorted((storage / "part" / message.stem).glob("*.json"))]
            text = _user_text(" ".join(part for part in parts if part))
            if text:
                prompts.append(text)
        return self._summary(prompts)

    def _database_prompts(self, database: Path, session_id: str) -> tuple[str, str, int, bool]:
        rows = _query(database,
                      "SELECT m.id AS message_id, p.data FROM message m JOIN part p ON p.message_id = m.id "
                      "WHERE m.session_id = ? AND json_valid(m.data) "
                      "AND json_extract(m.data, '$.role') = 'user' "
                      "ORDER BY m.time_created, m.id, p.time_created, p.id", (session_id,))
        messages: dict[str, list[str]] = {}
        for row in rows:
            text = self._part_text(_object(row.get("data")))
            if text:
                messages.setdefault(row["message_id"], []).append(text)
        return self._summary([clean_prompt(" ".join(parts)) for parts in messages.values()])

    def sources(self, root: Path, *, since: datetime, until: datetime | None = None) -> Iterator[SessionSource]:
        database = root / "opencode.db"
        rows = _query(database, "SELECT * FROM session")
        seen = {row.get("id") for row in rows}
        for row in rows:
            session_id = row.get("id")
            if not isinstance(session_id, str) or not re.fullmatch(r"ses_[a-zA-Z0-9]+", session_id):
                continue
            modified = from_epoch(row.get("time_updated")) or from_epoch(row.get("time_created"))
            if not modified or modified < since or (until and modified > until):
                continue
            yield SessionSource(session_id, database, row.get("project_id") or "opencode", modified,
                                metadata={"cwd": row.get("directory"), "version": row.get("version"),
                                          "started": from_epoch(row.get("time_created"))},
                                prompts=self._database_prompts(database, session_id),
                                title=clean_prompt(row.get("title"), limit=80))
        for transcript in self.transcripts(root):
            record = _read_object(transcript)
            session_id = record.get("id") or transcript.stem
            if not isinstance(session_id, str) or session_id in seen or not re.fullmatch(r"ses_[a-zA-Z0-9]+", session_id):
                continue
            seen.add(session_id)
            modified = from_epoch(_object(record.get("time")).get("updated"))
            modified = modified or super().activity(root, session_id, transcript)
            if not modified or modified < since or (until and modified > until):
                continue
            yield SessionSource(session_id, transcript, record.get("projectID") or transcript.parent.name,
                                modified, metadata=self.head(transcript), prompts=self.tail(transcript),
                                title=clean_prompt(record.get("title"), limit=80))

    def activity(self, root: Path, session_id: str, transcript: Path) -> datetime | None:
        if transcript.name == "opencode.db":
            rows = _query(transcript, "SELECT time_updated FROM session WHERE id = ?", (session_id,))
            return from_epoch(rows[0].get("time_updated")) if rows else None
        return from_epoch(_object(_read_object(transcript).get("time")).get("updated")) or super().activity(root, session_id, transcript)


AGENTS: dict[str, Agent] = {agent.key: agent for agent in (ClaudeCode(), Codex(), OpenCode())}
DEFAULT_AGENT = AGENTS["claude-code"]


def get_agent(key: str | None) -> Agent:
    if not key:
        return DEFAULT_AGENT
    try:
        return AGENTS[key]
    except KeyError:
        known = ", ".join(sorted(AGENTS))
        raise SystemExit(f"Unknown agent {key!r}. Known: {known}") from None


def installed_agents() -> list[Agent]:
    """Agents with a config directory on this machine, most useful first."""
    return [agent for agent in AGENTS.values() if agent.installed()]
